----------------------------------------------------------------------------------------------------
-- Hammerspoon Docs website config
--
local Ki = spoon.Ki
local Website = Ki.Website
local HammerspoonDocs = Website {
    name = "Hammerspoon Docs",
    url = "http://www.hammerspoon.org/docs/index.html",
    links = {
        { name = "Getting Started", link = "http://www.hammerspoon.org/go/" },
        { name = "GitHub - Hammerspoon/hammerspoon: Staggeringly powerful macOS desktop automation with Lua", link = "https://github.com/Hammerspoon/hammerspoon" },
        { name = "Hammerspoon docs: hs", link = "http://www.hammerspoon.org/docs/hs.html" },
        { name = "Hammerspoon docs: hs.alert", link = "http://www.hammerspoon.org/docs/hs.alert.html" },
        { name = "Hammerspoon docs: hs.appfinder", link = "http://www.hammerspoon.org/docs/hs.appfinder.html" },
        { name = "Hammerspoon docs: hs.applescript", link = "http://www.hammerspoon.org/docs/hs.applescript.html" },
        { name = "Hammerspoon docs: hs.application", link = "http://www.hammerspoon.org/docs/hs.application.html" },
        { name = "Hammerspoon docs: hs.application.watcher", link = "http://www.hammerspoon.org/docs/hs.application.watcher.html" },
        { name = "Hammerspoon docs: hs.audiodevice", link = "http://www.hammerspoon.org/docs/hs.audiodevice.html" },
        { name = "Hammerspoon docs: hs.audiodevice.datasource", link = "http://www.hammerspoon.org/docs/hs.audiodevice.datasource.html" },
        { name = "Hammerspoon docs: hs.audiodevice.watcher", link = "http://www.hammerspoon.org/docs/hs.audiodevice.watcher.html" },
        { name = "Hammerspoon docs: hs.base64", link = "http://www.hammerspoon.org/docs/hs.base64.html" },
        { name = "Hammerspoon docs: hs.battery", link = "http://www.hammerspoon.org/docs/hs.battery.html" },
        { name = "Hammerspoon docs: hs.battery.watcher", link = "http://www.hammerspoon.org/docs/hs.battery.watcher.html" },
        { name = "Hammerspoon docs: hs.bonjour", link = "http://www.hammerspoon.org/docs/hs.bonjour.html" },
        { name = "Hammerspoon docs: hs.bonjour.service", link = "http://www.hammerspoon.org/docs/hs.bonjour.service.html" },
        { name = "Hammerspoon docs: hs.brightness", link = "http://www.hammerspoon.org/docs/hs.brightness.html" },
        { name = "Hammerspoon docs: hs.caffeinate", link = "http://www.hammerspoon.org/docs/hs.caffeinate.html" },
        { name = "Hammerspoon docs: hs.caffeinate.watcher", link = "http://www.hammerspoon.org/docs/hs.caffeinate.watcher.html" },
        { name = "Hammerspoon docs: hs.canvas", link = "http://www.hammerspoon.org/docs/hs.canvas.html" },
        { name = "Hammerspoon docs: hs.canvas.matrix", link = "http://www.hammerspoon.org/docs/hs.canvas.matrix.html" },
        { name = "Hammerspoon docs: hs.chooser", link = "http://www.hammerspoon.org/docs/hs.chooser.html" },
        { name = "Hammerspoon docs: hs.console", link = "http://www.hammerspoon.org/docs/hs.console.html" },
        { name = "Hammerspoon docs: hs.crash", link = "http://www.hammerspoon.org/docs/hs.crash.html" },
        { name = "Hammerspoon docs: hs.deezer", link = "http://www.hammerspoon.org/docs/hs.deezer.html" },
        { name = "Hammerspoon docs: hs.dialog", link = "http://www.hammerspoon.org/docs/hs.dialog.html" },
        { name = "Hammerspoon docs: hs.dialog.color", link = "http://www.hammerspoon.org/docs/hs.dialog.color.html" },
        { name = "Hammerspoon docs: hs.distributednotifications", link = "http://www.hammerspoon.org/docs/hs.distributednotifications.html" },
        { name = "Hammerspoon docs: hs.doc", link = "http://www.hammerspoon.org/docs/hs.doc.html" },
        { name = "Hammerspoon docs: hs.doc.builder", link = "http://www.hammerspoon.org/docs/hs.doc.builder.html" },
        { name = "Hammerspoon docs: hs.doc.hsdocs", link = "http://www.hammerspoon.org/docs/hs.doc.hsdocs.html" },
        { name = "Hammerspoon docs: hs.doc.markdown", link = "http://www.hammerspoon.org/docs/hs.doc.markdown.html" },
        { name = "Hammerspoon docs: hs.dockicon", link = "http://www.hammerspoon.org/docs/hs.dockicon.html" },
        { name = "Hammerspoon docs: hs.drawing", link = "http://www.hammerspoon.org/docs/hs.drawing.html" },
        { name = "Hammerspoon docs: hs.drawing.color", link = "http://www.hammerspoon.org/docs/hs.drawing.color.html" },
        { name = "Hammerspoon docs: hs.eventtap", link = "http://www.hammerspoon.org/docs/hs.eventtap.html" },
        { name = "Hammerspoon docs: hs.eventtap.event", link = "http://www.hammerspoon.org/docs/hs.eventtap.event.html" },
        { name = "Hammerspoon docs: hs.expose", link = "http://www.hammerspoon.org/docs/hs.expose.html" },
        { name = "Hammerspoon docs: hs.fnutils", link = "http://www.hammerspoon.org/docs/hs.fnutils.html" },
        { name = "Hammerspoon docs: hs.fs", link = "http://www.hammerspoon.org/docs/hs.fs.html" },
        { name = "Hammerspoon docs: hs.fs.volume", link = "http://www.hammerspoon.org/docs/hs.fs.volume.html" },
        { name = "Hammerspoon docs: hs.fs.xattr", link = "http://www.hammerspoon.org/docs/hs.fs.xattr.html" },
        { name = "Hammerspoon docs: hs.geometry", link = "http://www.hammerspoon.org/docs/hs.geometry.html" },
        { name = "Hammerspoon docs: hs.grid", link = "http://www.hammerspoon.org/docs/hs.grid.html" },
        { name = "Hammerspoon docs: hs.hash", link = "http://www.hammerspoon.org/docs/hs.hash.html" },
        { name = "Hammerspoon docs: hs.hid", link = "http://www.hammerspoon.org/docs/hs.hid.html" },
        { name = "Hammerspoon docs: hs.hid.led", link = "http://www.hammerspoon.org/docs/hs.hid.led.html" },
        { name = "Hammerspoon docs: hs.hints", link = "http://www.hammerspoon.org/docs/hs.hints.html" },
        { name = "Hammerspoon docs: hs.host", link = "http://www.hammerspoon.org/docs/hs.host.html" },
        { name = "Hammerspoon docs: hs.host.locale", link = "http://www.hammerspoon.org/docs/hs.host.locale.html" },
        { name = "Hammerspoon docs: hs.hotkey", link = "http://www.hammerspoon.org/docs/hs.hotkey.html" },
        { name = "Hammerspoon docs: hs.hotkey.modal", link = "http://www.hammerspoon.org/docs/hs.hotkey.modal.html" },
        { name = "Hammerspoon docs: hs.http", link = "http://www.hammerspoon.org/docs/hs.http.html" },
        { name = "Hammerspoon docs: hs.httpserver", link = "http://www.hammerspoon.org/docs/hs.httpserver.html" },
        { name = "Hammerspoon docs: hs.httpserver.hsminweb", link = "http://www.hammerspoon.org/docs/hs.httpserver.hsminweb.html" },
        { name = "Hammerspoon docs: hs.httpserver.hsminweb.cgilua", link = "http://www.hammerspoon.org/docs/hs.httpserver.hsminweb.cgilua.html" },
        { name = "Hammerspoon docs: hs.httpserver.hsminweb.cgilua.lp", link = "http://www.hammerspoon.org/docs/hs.httpserver.hsminweb.cgilua.lp.html" },
        { name = "Hammerspoon docs: hs.httpserver.hsminweb.cgilua.urlcode", link = "http://www.hammerspoon.org/docs/hs.httpserver.hsminweb.cgilua.urlcode.html" },
        { name = "Hammerspoon docs: hs.image", link = "http://www.hammerspoon.org/docs/hs.image.html" },
        { name = "Hammerspoon docs: hs.inspect", link = "http://www.hammerspoon.org/docs/hs.inspect.html" },
        { name = "Hammerspoon docs: hs.ipc", link = "http://www.hammerspoon.org/docs/hs.ipc.html" },
        { name = "Hammerspoon docs: hs.itunes", link = "http://www.hammerspoon.org/docs/hs.itunes.html" },
        { name = "Hammerspoon docs: hs.javascript", link = "http://www.hammerspoon.org/docs/hs.javascript.html" },
        { name = "Hammerspoon docs: hs.json", link = "http://www.hammerspoon.org/docs/hs.json.html" },
        { name = "Hammerspoon docs: hs.keycodes", link = "http://www.hammerspoon.org/docs/hs.keycodes.html" },
        { name = "Hammerspoon docs: hs.layout", link = "http://www.hammerspoon.org/docs/hs.layout.html" },
        { name = "Hammerspoon docs: hs.location", link = "http://www.hammerspoon.org/docs/hs.location.html" },
        { name = "Hammerspoon docs: hs.location.geocoder", link = "http://www.hammerspoon.org/docs/hs.location.geocoder.html" },
        { name = "Hammerspoon docs: hs.logger", link = "http://www.hammerspoon.org/docs/hs.logger.html" },
        { name = "Hammerspoon docs: hs.math", link = "http://www.hammerspoon.org/docs/hs.math.html" },
        { name = "Hammerspoon docs: hs.menubar", link = "http://www.hammerspoon.org/docs/hs.menubar.html" },
        { name = "Hammerspoon docs: hs.messages", link = "http://www.hammerspoon.org/docs/hs.messages.html" },
        { name = "Hammerspoon docs: hs.midi", link = "http://www.hammerspoon.org/docs/hs.midi.html" },
        { name = "Hammerspoon docs: hs.milight", link = "http://www.hammerspoon.org/docs/hs.milight.html" },
        { name = "Hammerspoon docs: hs.mjomatic", link = "http://www.hammerspoon.org/docs/hs.mjomatic.html" },
        { name = "Hammerspoon docs: hs.mouse", link = "http://www.hammerspoon.org/docs/hs.mouse.html" },
        { name = "Hammerspoon docs: hs.network", link = "http://www.hammerspoon.org/docs/hs.network.html" },
        { name = "Hammerspoon docs: hs.network.configuration", link = "http://www.hammerspoon.org/docs/hs.network.configuration.html" },
        { name = "Hammerspoon docs: hs.network.host", link = "http://www.hammerspoon.org/docs/hs.network.host.html" },
        { name = "Hammerspoon docs: hs.network.ping", link = "http://www.hammerspoon.org/docs/hs.network.ping.html" },
        { name = "Hammerspoon docs: hs.network.ping.echoRequest", link = "http://www.hammerspoon.org/docs/hs.network.ping.echoRequest.html" },
        { name = "Hammerspoon docs: hs.network.reachability", link = "http://www.hammerspoon.org/docs/hs.network.reachability.html" },
        { name = "Hammerspoon docs: hs.noises", link = "http://www.hammerspoon.org/docs/hs.noises.html" },
        { name = "Hammerspoon docs: hs.notify", link = "http://www.hammerspoon.org/docs/hs.notify.html" },
        { name = "Hammerspoon docs: hs.osascript", link = "http://www.hammerspoon.org/docs/hs.osascript.html" },
        { name = "Hammerspoon docs: hs.pasteboard", link = "http://www.hammerspoon.org/docs/hs.pasteboard.html" },
        { name = "Hammerspoon docs: hs.pathwatcher", link = "http://www.hammerspoon.org/docs/hs.pathwatcher.html" },
        { name = "Hammerspoon docs: hs.plist", link = "http://www.hammerspoon.org/docs/hs.plist.html" },
        { name = "Hammerspoon docs: hs.redshift", link = "http://www.hammerspoon.org/docs/hs.redshift.html" },
        { name = "Hammerspoon docs: hs.screen", link = "http://www.hammerspoon.org/docs/hs.screen.html" },
        { name = "Hammerspoon docs: hs.screen.watcher", link = "http://www.hammerspoon.org/docs/hs.screen.watcher.html" },
        { name = "Hammerspoon docs: hs.settings", link = "http://www.hammerspoon.org/docs/hs.settings.html" },
        { name = "Hammerspoon docs: hs.sharing", link = "http://www.hammerspoon.org/docs/hs.sharing.html" },
        { name = "Hammerspoon docs: hs.socket", link = "http://www.hammerspoon.org/docs/hs.socket.html" },
        { name = "Hammerspoon docs: hs.socket.udp", link = "http://www.hammerspoon.org/docs/hs.socket.udp.html" },
        { name = "Hammerspoon docs: hs.sound", link = "http://www.hammerspoon.org/docs/hs.sound.html" },
        { name = "Hammerspoon docs: hs.spaces.watcher", link = "http://www.hammerspoon.org/docs/hs.spaces.watcher.html" },
        { name = "Hammerspoon docs: hs.speech", link = "http://www.hammerspoon.org/docs/hs.speech.html" },
        { name = "Hammerspoon docs: hs.speech.listener", link = "http://www.hammerspoon.org/docs/hs.speech.listener.html" },
        { name = "Hammerspoon docs: hs.spoons", link = "http://www.hammerspoon.org/docs/hs.spoons.html" },
        { name = "Hammerspoon docs: hs.spotify", link = "http://www.hammerspoon.org/docs/hs.spotify.html" },
        { name = "Hammerspoon docs: hs.spotlight", link = "http://www.hammerspoon.org/docs/hs.spotlight.html" },
        { name = "Hammerspoon docs: hs.spotlight.group", link = "http://www.hammerspoon.org/docs/hs.spotlight.group.html" },
        { name = "Hammerspoon docs: hs.spotlight.item", link = "http://www.hammerspoon.org/docs/hs.spotlight.item.html" },
        { name = "Hammerspoon docs: hs.sqlite3", link = "http://www.hammerspoon.org/docs/hs.sqlite3.html" },
        { name = "Hammerspoon docs: hs.streamdeck", link = "http://www.hammerspoon.org/docs/hs.streamdeck.html" },
        { name = "Hammerspoon docs: hs.styledtext", link = "http://www.hammerspoon.org/docs/hs.styledtext.html" },
        { name = "Hammerspoon docs: hs.tabs", link = "http://www.hammerspoon.org/docs/hs.tabs.html" },
        { name = "Hammerspoon docs: hs.tangent", link = "http://www.hammerspoon.org/docs/hs.tangent.html" },
        { name = "Hammerspoon docs: hs.task", link = "http://www.hammerspoon.org/docs/hs.task.html" },
        { name = "Hammerspoon docs: hs.timer", link = "http://www.hammerspoon.org/docs/hs.timer.html" },
        { name = "Hammerspoon docs: hs.timer.delayed", link = "http://www.hammerspoon.org/docs/hs.timer.delayed.html" },
        { name = "Hammerspoon docs: hs.uielement", link = "http://www.hammerspoon.org/docs/hs.uielement.html" },
        { name = "Hammerspoon docs: hs.uielement.watcher", link = "http://www.hammerspoon.org/docs/hs.uielement.watcher.html" },
        { name = "Hammerspoon docs: hs.urlevent", link = "http://www.hammerspoon.org/docs/hs.urlevent.html" },
        { name = "Hammerspoon docs: hs.usb", link = "http://www.hammerspoon.org/docs/hs.usb.html" },
        { name = "Hammerspoon docs: hs.usb.watcher", link = "http://www.hammerspoon.org/docs/hs.usb.watcher.html" },
        { name = "Hammerspoon docs: hs.utf8", link = "http://www.hammerspoon.org/docs/hs.utf8.html" },
        { name = "Hammerspoon docs: hs.vox", link = "http://www.hammerspoon.org/docs/hs.vox.html" },
        { name = "Hammerspoon docs: hs.watchable", link = "http://www.hammerspoon.org/docs/hs.watchable.html" },
        { name = "Hammerspoon docs: hs.webview", link = "http://www.hammerspoon.org/docs/hs.webview.html" },
        { name = "Hammerspoon docs: hs.webview.datastore", link = "http://www.hammerspoon.org/docs/hs.webview.datastore.html" },
        { name = "Hammerspoon docs: hs.webview.toolbar", link = "http://www.hammerspoon.org/docs/hs.webview.toolbar.html" },
        { name = "Hammerspoon docs: hs.webview.usercontent", link = "http://www.hammerspoon.org/docs/hs.webview.usercontent.html" },
        { name = "Hammerspoon docs: hs.wifi", link = "http://www.hammerspoon.org/docs/hs.wifi.html" },
        { name = "Hammerspoon docs: hs.wifi.watcher", link = "http://www.hammerspoon.org/docs/hs.wifi.watcher.html" },
        { name = "Hammerspoon docs: hs.window", link = "http://www.hammerspoon.org/docs/hs.window.html" },
        { name = "Hammerspoon docs: hs.window.filter", link = "http://www.hammerspoon.org/docs/hs.window.filter.html" },
        { name = "Hammerspoon docs: hs.window.highlight", link = "http://www.hammerspoon.org/docs/hs.window.highlight.html" },
        { name = "Hammerspoon docs: hs.window.layout", link = "http://www.hammerspoon.org/docs/hs.window.layout.html" },
        { name = "Hammerspoon docs: hs.window.switcher", link = "http://www.hammerspoon.org/docs/hs.window.switcher.html" },
        { name = "Hammerspoon docs: hs.window.tiling", link = "http://www.hammerspoon.org/docs/hs.window.tiling.html" },
        { name = "Hammerspoon Spoons Docs", link = "http://www.hammerspoon.org/Spoons" },
        { name = "hammerspoon/SPOONS.md at master · Hammerspoon/hammerspoon · GitHub", link = "https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md" },
        { name = "Skin.h", link = "http://www.hammerspoon.org/docs/LuaSkin/" }
    },
}

return HammerspoonDocs
