----------------------------------------------------------------------------------------------------
-- LearnXInYMinutes website config
--
-- JavaScript to retrieve docs items:
-- copy(
--     Array.from(document.querySelectorAll(".name > a"))
--         .map((node) => `{ name = "${node.innerText}", link = "${node.href}" }`)
--         .join("\n")
-- );
local Website = spoon.Ki.Website

return Website:new("Learn X in Y Minutes", "https://learnxinyminutes.com", {
    { name = "Asymptotic Notation", link = "https://learnxinyminutes.com/docs/asymptotic-notation/" },
    { name = "Dynamic Programming", link = "https://learnxinyminutes.com/docs/dynamic-programming/" },
    { name = "Lambda Calculus", link = "https://learnxinyminutes.com/docs/lambda-calculus/" },
    { name = "asciidoc", link = "https://learnxinyminutes.com/docs/asciidoc/" },
    { name = "bc", link = "https://learnxinyminutes.com/docs/bc/" },
    { name = "bf", link = "https://learnxinyminutes.com/docs/bf/" },
    { name = "c", link = "https://learnxinyminutes.com/docs/c/" },
    { name = "c#", link = "https://learnxinyminutes.com/docs/csharp/" },
    { name = "c++", link = "https://learnxinyminutes.com/docs/c++/" },
    { name = "chapel", link = "https://learnxinyminutes.com/docs/chapel/" },
    { name = "CHICKEN", link = "https://learnxinyminutes.com/docs/CHICKEN/" },
    { name = "clojure", link = "https://learnxinyminutes.com/docs/clojure/" },
    { name = "clojure macros", link = "https://learnxinyminutes.com/docs/clojure-macros/" },
    { name = "COBOL", link = "https://learnxinyminutes.com/docs/cobol/" },
    { name = "coffeescript", link = "https://learnxinyminutes.com/docs/coffeescript/" },
    { name = "coldfusion", link = "https://learnxinyminutes.com/docs/coldfusion/" },
    { name = "Common Lisp", link = "https://learnxinyminutes.com/docs/common-lisp/" },
    { name = "Coq", link = "https://learnxinyminutes.com/docs/coq/" },
    { name = "crystal", link = "https://learnxinyminutes.com/docs/crystal/" },
    { name = "css", link = "https://learnxinyminutes.com/docs/css/" },
    { name = "cypher", link = "https://learnxinyminutes.com/docs/cypher/" },
    { name = "D", link = "https://learnxinyminutes.com/docs/d/" },
    { name = "dart", link = "https://learnxinyminutes.com/docs/dart/" },
    { name = "Dhall", link = "https://learnxinyminutes.com/docs/dhall/" },
    { name = "docker", link = "https://learnxinyminutes.com/docs/docker/" },
    { name = "edn", link = "https://learnxinyminutes.com/docs/edn/" },
    { name = "elisp", link = "https://learnxinyminutes.com/docs/elisp/" },
    { name = "elixir", link = "https://learnxinyminutes.com/docs/elixir/" },
    { name = "Elm", link = "https://learnxinyminutes.com/docs/elm/" },
    { name = "erlang", link = "https://learnxinyminutes.com/docs/erlang/" },
    { name = "F#", link = "https://learnxinyminutes.com/docs/fsharp/" },
    { name = "factor", link = "https://learnxinyminutes.com/docs/factor/" },
    { name = "forth", link = "https://learnxinyminutes.com/docs/forth/" },
    { name = "Fortran", link = "https://learnxinyminutes.com/docs/fortran95/" },
    { name = "Go", link = "https://learnxinyminutes.com/docs/go/" },
    { name = "Groovy", link = "https://learnxinyminutes.com/docs/groovy/" },
    { name = "Hack", link = "https://learnxinyminutes.com/docs/hack/" },
    { name = "haml", link = "https://learnxinyminutes.com/docs/haml/" },
    { name = "Haskell", link = "https://learnxinyminutes.com/docs/haskell/" },
    { name = "haxe", link = "https://learnxinyminutes.com/docs/haxe/" },
    { name = "hdl", link = "https://learnxinyminutes.com/docs/hdl/" },
    { name = "HQ9+", link = "https://learnxinyminutes.com/docs/hq9+/" },
    { name = "html", link = "https://learnxinyminutes.com/docs/html/" },
    { name = "hy", link = "https://learnxinyminutes.com/docs/hy/" },
    { name = "Inform7", link = "https://learnxinyminutes.com/docs/inform7/" },
    { name = "java", link = "https://learnxinyminutes.com/docs/java/" },
    { name = "javascript", link = "https://learnxinyminutes.com/docs/javascript/" },
    { name = "json", link = "https://learnxinyminutes.com/docs/json/" },
    { name = "Julia", link = "https://learnxinyminutes.com/docs/julia/" },
    { name = "kdb+", link = "https://learnxinyminutes.com/docs/kdb+/" },
    { name = "kotlin", link = "https://learnxinyminutes.com/docs/kotlin/" },
    { name = "latex", link = "https://learnxinyminutes.com/docs/latex/" },
    { name = "LDPL", link = "https://learnxinyminutes.com/docs/ldpl/" },
    { name = "less", link = "https://learnxinyminutes.com/docs/less/" },
    { name = "Lisp Flavoured Erlang(LFE)", link = "https://learnxinyminutes.com/docs/lfe/" },
    { name = "LiveScript", link = "https://learnxinyminutes.com/docs/livescript/" },
    { name = "Logtalk", link = "https://learnxinyminutes.com/docs/logtalk/" },
    { name = "LOLCODE", link = "https://learnxinyminutes.com/docs/LOLCODE/" },
    { name = "Lua", link = "https://learnxinyminutes.com/docs/lua/" },
    { name = "M (MUMPS)", link = "https://learnxinyminutes.com/docs/m/" },
    { name = "markdown", link = "https://learnxinyminutes.com/docs/markdown/" },
    { name = "Matlab", link = "https://learnxinyminutes.com/docs/matlab/" },
    { name = "mercury", link = "https://learnxinyminutes.com/docs/mercury/" },
    { name = "MIPS Assembly", link = "https://learnxinyminutes.com/docs/mips/" },
    { name = "montilang", link = "https://learnxinyminutes.com/docs/montilang/" },
    { name = "moonscript", link = "https://learnxinyminutes.com/docs/moonscript/" },
    { name = "neat", link = "https://learnxinyminutes.com/docs/neat/" },
    { name = "Nim", link = "https://learnxinyminutes.com/docs/nim/" },
    { name = "nix", link = "https://learnxinyminutes.com/docs/nix/" },
    { name = "Objective-C", link = "https://learnxinyminutes.com/docs/objective-c/" },
    { name = "OCaml", link = "https://learnxinyminutes.com/docs/ocaml/" },
    { name = "Paren", link = "https://learnxinyminutes.com/docs/paren/" },
    { name = "Pascal", link = "https://learnxinyminutes.com/docs/pascal/" },
    { name = "PCRE", link = "https://learnxinyminutes.com/docs/pcre/" },
    { name = "perl", link = "https://learnxinyminutes.com/docs/perl/" },
    { name = "PHP", link = "https://learnxinyminutes.com/docs/php/" },
    { name = "Pod", link = "https://learnxinyminutes.com/docs/perl6-pod/" },
    { name = "pogoscript", link = "https://learnxinyminutes.com/docs/pogo/" },
    { name = "processing", link = "https://learnxinyminutes.com/docs/processing/" },
    { name = "prolog", link = "https://learnxinyminutes.com/docs/prolog/" },
    { name = "protocol-buffers", link = "https://learnxinyminutes.com/docs/protocol-buffer-3/" },
    { name = "Pug", link = "https://learnxinyminutes.com/docs/pug/" },
    { name = "purescript", link = "https://learnxinyminutes.com/docs/purescript/" },
    { name = "Python", link = "https://learnxinyminutes.com/docs/python/" },
    { name = "Python 2 (legacy)", link = "https://learnxinyminutes.com/docs/pythonlegacy/" },
    { name = "R", link = "https://learnxinyminutes.com/docs/r/" },
    { name = "racket", link = "https://learnxinyminutes.com/docs/racket/" },
    { name = "Raku", link = "https://learnxinyminutes.com/docs/raku/" },
    { name = "reason", link = "https://learnxinyminutes.com/docs/reason/" },
    { name = "Red", link = "https://learnxinyminutes.com/docs/red/" },
    { name = "restructured text (RST)", link = "https://learnxinyminutes.com/docs/rst/" },
    { name = "ruby", link = "https://learnxinyminutes.com/docs/ruby/" },
    { name = "Rust", link = "https://learnxinyminutes.com/docs/rust/" },
    { name = "sass", link = "https://learnxinyminutes.com/docs/sass/" },
    { name = "Scala", link = "https://learnxinyminutes.com/docs/scala/" },
    { name = "self", link = "https://learnxinyminutes.com/docs/self/" },
    { name = "SmallBASIC", link = "https://learnxinyminutes.com/docs/smallbasic/" },
    { name = "Smalltalk", link = "https://learnxinyminutes.com/docs/smalltalk/" },
    { name = "Solidity", link = "https://learnxinyminutes.com/docs/solidity/" },
    { name = "SQL", link = "https://learnxinyminutes.com/docs/sql/" },
    { name = "Standard ML", link = "https://learnxinyminutes.com/docs/standard-ml/" },
    { name = "stylus", link = "https://learnxinyminutes.com/docs/stylus/" },
    { name = "swift", link = "https://learnxinyminutes.com/docs/swift/" },
    { name = "Tcl", link = "https://learnxinyminutes.com/docs/tcl/" },
    { name = "textile", link = "https://learnxinyminutes.com/docs/textile/" },
    { name = "toml", link = "https://learnxinyminutes.com/docs/toml/" },
    { name = "TypeScript", link = "https://learnxinyminutes.com/docs/typescript/" },
    { name = "vala", link = "https://learnxinyminutes.com/docs/vala/" },
    { name = "Vimscript", link = "https://learnxinyminutes.com/docs/vimscript/" },
    { name = "Visual Basic", link = "https://learnxinyminutes.com/docs/visualbasic/" },
    { name = "Vyper", link = "https://learnxinyminutes.com/docs/vyper/" },
    { name = "WebAssembly", link = "https://learnxinyminutes.com/docs/wasm/" },
    { name = "whip", link = "https://learnxinyminutes.com/docs/whip/" },
    { name = "wolfram", link = "https://learnxinyminutes.com/docs/wolfram/" },
    { name = "xml", link = "https://learnxinyminutes.com/docs/xml/" },
    { name = "yaml", link = "https://learnxinyminutes.com/docs/yaml/" },
    { name = "amd", link = "https://learnxinyminutes.com/docs/amd/" },
    { name = "AngularJS", link = "https://learnxinyminutes.com/docs/angularjs/" },
    { name = "ansible", link = "https://learnxinyminutes.com/docs/ansible/" },
    { name = "awk", link = "https://learnxinyminutes.com/docs/awk/" },
    { name = "bash", link = "https://learnxinyminutes.com/docs/bash/" },
    { name = "cmake", link = "https://learnxinyminutes.com/docs/cmake/" },
    { name = "compojure", link = "https://learnxinyminutes.com/docs/compojure/" },
    { name = "composer", link = "https://learnxinyminutes.com/docs/php-composer/" },
    { name = "DirectX 9", link = "https://learnxinyminutes.com/docs/directx9/" },
    { name = "emacs", link = "https://learnxinyminutes.com/docs/emacs/" },
    { name = "git", link = "https://learnxinyminutes.com/docs/git/" },
    { name = "jquery", link = "https://learnxinyminutes.com/docs/jquery/" },
    { name = "linker", link = "https://learnxinyminutes.com/docs/linker/" },
    { name = "make", link = "https://learnxinyminutes.com/docs/make/" },
    { name = "Mercurial", link = "https://learnxinyminutes.com/docs/mercurial/" },
    { name = "messagepack", link = "https://learnxinyminutes.com/docs/messagepack/" },
    { name = "OpenCV", link = "https://learnxinyminutes.com/docs/opencv/" },
    { name = "OpenGL", link = "https://learnxinyminutes.com/docs/opengl/" },
    { name = "p5", link = "https://learnxinyminutes.com/docs/p5/" },
    { name = "powershell", link = "https://learnxinyminutes.com/docs/powershell/" },
    { name = "PyQT", link = "https://learnxinyminutes.com/docs/pyqt/" },
    { name = "Qt Framework", link = "https://learnxinyminutes.com/docs/qt/" },
    { name = "ruby ecosystem", link = "https://learnxinyminutes.com/docs/ruby-ecosystem/" },
    { name = "ShutIt", link = "https://learnxinyminutes.com/docs/shutit/" },
    { name = "Statistical Computing with Python", link = "https://learnxinyminutes.com/docs/pythonstatcomp/" },
    { name = "tcsh", link = "https://learnxinyminutes.com/docs/tcsh/" },
    { name = "tmux", link = "https://learnxinyminutes.com/docs/tmux/" },
    { name = "vim", link = "https://learnxinyminutes.com/docs/vim/" },
    { name = "zfs", link = "https://learnxinyminutes.com/docs/zfs/" },
})
