----------------------------------------------------------------------------------------------------
-- LearnXInYMinutes URL entity
--
local URL = spoon.Ki.URL
local baseURL = "https://learnxinyminutes.com"
local LearnXInYMinutes = URL:new(baseURL)

-- JavaScript to retrieve docs items:
-- copy(
--     Array.from(document.querySelectorAll(".name > a"))
--         .map((node) => `{ name = "${node.innerText}", path = "${node.href}" }`)
--         .join("\n")
-- );
LearnXInYMinutes.paths = {
    { name = "Asymptotic Notation", path = "https://learnxinyminutes.com/docs/asymptotic-notation/" },
    { name = "Dynamic Programming", path = "https://learnxinyminutes.com/docs/dynamic-programming/" },
    { name = "Lambda Calculus", path = "https://learnxinyminutes.com/docs/lambda-calculus/" },
    { name = "asciidoc", path = "https://learnxinyminutes.com/docs/asciidoc/" },
    { name = "bc", path = "https://learnxinyminutes.com/docs/bc/" },
    { name = "bf", path = "https://learnxinyminutes.com/docs/bf/" },
    { name = "c", path = "https://learnxinyminutes.com/docs/c/" },
    { name = "c#", path = "https://learnxinyminutes.com/docs/csharp/" },
    { name = "c++", path = "https://learnxinyminutes.com/docs/c++/" },
    { name = "chapel", path = "https://learnxinyminutes.com/docs/chapel/" },
    { name = "CHICKEN", path = "https://learnxinyminutes.com/docs/CHICKEN/" },
    { name = "clojure", path = "https://learnxinyminutes.com/docs/clojure/" },
    { name = "clojure macros", path = "https://learnxinyminutes.com/docs/clojure-macros/" },
    { name = "COBOL", path = "https://learnxinyminutes.com/docs/cobol/" },
    { name = "coffeescript", path = "https://learnxinyminutes.com/docs/coffeescript/" },
    { name = "coldfusion", path = "https://learnxinyminutes.com/docs/coldfusion/" },
    { name = "Common Lisp", path = "https://learnxinyminutes.com/docs/common-lisp/" },
    { name = "Coq", path = "https://learnxinyminutes.com/docs/coq/" },
    { name = "crystal", path = "https://learnxinyminutes.com/docs/crystal/" },
    { name = "css", path = "https://learnxinyminutes.com/docs/css/" },
    { name = "cypher", path = "https://learnxinyminutes.com/docs/cypher/" },
    { name = "D", path = "https://learnxinyminutes.com/docs/d/" },
    { name = "dart", path = "https://learnxinyminutes.com/docs/dart/" },
    { name = "Dhall", path = "https://learnxinyminutes.com/docs/dhall/" },
    { name = "docker", path = "https://learnxinyminutes.com/docs/docker/" },
    { name = "edn", path = "https://learnxinyminutes.com/docs/edn/" },
    { name = "elisp", path = "https://learnxinyminutes.com/docs/elisp/" },
    { name = "elixir", path = "https://learnxinyminutes.com/docs/elixir/" },
    { name = "Elm", path = "https://learnxinyminutes.com/docs/elm/" },
    { name = "erlang", path = "https://learnxinyminutes.com/docs/erlang/" },
    { name = "F#", path = "https://learnxinyminutes.com/docs/fsharp/" },
    { name = "factor", path = "https://learnxinyminutes.com/docs/factor/" },
    { name = "forth", path = "https://learnxinyminutes.com/docs/forth/" },
    { name = "Fortran", path = "https://learnxinyminutes.com/docs/fortran95/" },
    { name = "Go", path = "https://learnxinyminutes.com/docs/go/" },
    { name = "Groovy", path = "https://learnxinyminutes.com/docs/groovy/" },
    { name = "Hack", path = "https://learnxinyminutes.com/docs/hack/" },
    { name = "haml", path = "https://learnxinyminutes.com/docs/haml/" },
    { name = "Haskell", path = "https://learnxinyminutes.com/docs/haskell/" },
    { name = "haxe", path = "https://learnxinyminutes.com/docs/haxe/" },
    { name = "hdl", path = "https://learnxinyminutes.com/docs/hdl/" },
    { name = "HQ9+", path = "https://learnxinyminutes.com/docs/hq9+/" },
    { name = "html", path = "https://learnxinyminutes.com/docs/html/" },
    { name = "hy", path = "https://learnxinyminutes.com/docs/hy/" },
    { name = "Inform7", path = "https://learnxinyminutes.com/docs/inform7/" },
    { name = "java", path = "https://learnxinyminutes.com/docs/java/" },
    { name = "javascript", path = "https://learnxinyminutes.com/docs/javascript/" },
    { name = "json", path = "https://learnxinyminutes.com/docs/json/" },
    { name = "Julia", path = "https://learnxinyminutes.com/docs/julia/" },
    { name = "kdb+", path = "https://learnxinyminutes.com/docs/kdb+/" },
    { name = "kotlin", path = "https://learnxinyminutes.com/docs/kotlin/" },
    { name = "latex", path = "https://learnxinyminutes.com/docs/latex/" },
    { name = "LDPL", path = "https://learnxinyminutes.com/docs/ldpl/" },
    { name = "less", path = "https://learnxinyminutes.com/docs/less/" },
    { name = "Lisp Flavoured Erlang(LFE)", path = "https://learnxinyminutes.com/docs/lfe/" },
    { name = "LiveScript", path = "https://learnxinyminutes.com/docs/livescript/" },
    { name = "Logtalk", path = "https://learnxinyminutes.com/docs/logtalk/" },
    { name = "LOLCODE", path = "https://learnxinyminutes.com/docs/LOLCODE/" },
    { name = "Lua", path = "https://learnxinyminutes.com/docs/lua/" },
    { name = "M (MUMPS)", path = "https://learnxinyminutes.com/docs/m/" },
    { name = "markdown", path = "https://learnxinyminutes.com/docs/markdown/" },
    { name = "Matlab", path = "https://learnxinyminutes.com/docs/matlab/" },
    { name = "mercury", path = "https://learnxinyminutes.com/docs/mercury/" },
    { name = "MIPS Assembly", path = "https://learnxinyminutes.com/docs/mips/" },
    { name = "montilang", path = "https://learnxinyminutes.com/docs/montilang/" },
    { name = "moonscript", path = "https://learnxinyminutes.com/docs/moonscript/" },
    { name = "neat", path = "https://learnxinyminutes.com/docs/neat/" },
    { name = "Nim", path = "https://learnxinyminutes.com/docs/nim/" },
    { name = "nix", path = "https://learnxinyminutes.com/docs/nix/" },
    { name = "Objective-C", path = "https://learnxinyminutes.com/docs/objective-c/" },
    { name = "OCaml", path = "https://learnxinyminutes.com/docs/ocaml/" },
    { name = "Paren", path = "https://learnxinyminutes.com/docs/paren/" },
    { name = "Pascal", path = "https://learnxinyminutes.com/docs/pascal/" },
    { name = "PCRE", path = "https://learnxinyminutes.com/docs/pcre/" },
    { name = "perl", path = "https://learnxinyminutes.com/docs/perl/" },
    { name = "PHP", path = "https://learnxinyminutes.com/docs/php/" },
    { name = "Pod", path = "https://learnxinyminutes.com/docs/perl6-pod/" },
    { name = "pogoscript", path = "https://learnxinyminutes.com/docs/pogo/" },
    { name = "processing", path = "https://learnxinyminutes.com/docs/processing/" },
    { name = "prolog", path = "https://learnxinyminutes.com/docs/prolog/" },
    { name = "protocol-buffers", path = "https://learnxinyminutes.com/docs/protocol-buffer-3/" },
    { name = "Pug", path = "https://learnxinyminutes.com/docs/pug/" },
    { name = "purescript", path = "https://learnxinyminutes.com/docs/purescript/" },
    { name = "Python", path = "https://learnxinyminutes.com/docs/python/" },
    { name = "Python 2 (legacy)", path = "https://learnxinyminutes.com/docs/pythonlegacy/" },
    { name = "R", path = "https://learnxinyminutes.com/docs/r/" },
    { name = "racket", path = "https://learnxinyminutes.com/docs/racket/" },
    { name = "Raku", path = "https://learnxinyminutes.com/docs/raku/" },
    { name = "reason", path = "https://learnxinyminutes.com/docs/reason/" },
    { name = "Red", path = "https://learnxinyminutes.com/docs/red/" },
    { name = "restructured text (RST)", path = "https://learnxinyminutes.com/docs/rst/" },
    { name = "ruby", path = "https://learnxinyminutes.com/docs/ruby/" },
    { name = "Rust", path = "https://learnxinyminutes.com/docs/rust/" },
    { name = "sass", path = "https://learnxinyminutes.com/docs/sass/" },
    { name = "Scala", path = "https://learnxinyminutes.com/docs/scala/" },
    { name = "self", path = "https://learnxinyminutes.com/docs/self/" },
    { name = "SmallBASIC", path = "https://learnxinyminutes.com/docs/smallbasic/" },
    { name = "Smalltalk", path = "https://learnxinyminutes.com/docs/smalltalk/" },
    { name = "Solidity", path = "https://learnxinyminutes.com/docs/solidity/" },
    { name = "SQL", path = "https://learnxinyminutes.com/docs/sql/" },
    { name = "Standard ML", path = "https://learnxinyminutes.com/docs/standard-ml/" },
    { name = "stylus", path = "https://learnxinyminutes.com/docs/stylus/" },
    { name = "swift", path = "https://learnxinyminutes.com/docs/swift/" },
    { name = "Tcl", path = "https://learnxinyminutes.com/docs/tcl/" },
    { name = "textile", path = "https://learnxinyminutes.com/docs/textile/" },
    { name = "toml", path = "https://learnxinyminutes.com/docs/toml/" },
    { name = "TypeScript", path = "https://learnxinyminutes.com/docs/typescript/" },
    { name = "vala", path = "https://learnxinyminutes.com/docs/vala/" },
    { name = "Vimscript", path = "https://learnxinyminutes.com/docs/vimscript/" },
    { name = "Visual Basic", path = "https://learnxinyminutes.com/docs/visualbasic/" },
    { name = "Vyper", path = "https://learnxinyminutes.com/docs/vyper/" },
    { name = "WebAssembly", path = "https://learnxinyminutes.com/docs/wasm/" },
    { name = "whip", path = "https://learnxinyminutes.com/docs/whip/" },
    { name = "wolfram", path = "https://learnxinyminutes.com/docs/wolfram/" },
    { name = "xml", path = "https://learnxinyminutes.com/docs/xml/" },
    { name = "yaml", path = "https://learnxinyminutes.com/docs/yaml/" },
    { name = "amd", path = "https://learnxinyminutes.com/docs/amd/" },
    { name = "AngularJS", path = "https://learnxinyminutes.com/docs/angularjs/" },
    { name = "ansible", path = "https://learnxinyminutes.com/docs/ansible/" },
    { name = "awk", path = "https://learnxinyminutes.com/docs/awk/" },
    { name = "bash", path = "https://learnxinyminutes.com/docs/bash/" },
    { name = "cmake", path = "https://learnxinyminutes.com/docs/cmake/" },
    { name = "compojure", path = "https://learnxinyminutes.com/docs/compojure/" },
    { name = "composer", path = "https://learnxinyminutes.com/docs/php-composer/" },
    { name = "DirectX 9", path = "https://learnxinyminutes.com/docs/directx9/" },
    { name = "emacs", path = "https://learnxinyminutes.com/docs/emacs/" },
    { name = "git", path = "https://learnxinyminutes.com/docs/git/" },
    { name = "jquery", path = "https://learnxinyminutes.com/docs/jquery/" },
    { name = "linker", path = "https://learnxinyminutes.com/docs/linker/" },
    { name = "make", path = "https://learnxinyminutes.com/docs/make/" },
    { name = "Mercurial", path = "https://learnxinyminutes.com/docs/mercurial/" },
    { name = "messagepack", path = "https://learnxinyminutes.com/docs/messagepack/" },
    { name = "OpenCV", path = "https://learnxinyminutes.com/docs/opencv/" },
    { name = "OpenGL", path = "https://learnxinyminutes.com/docs/opengl/" },
    { name = "p5", path = "https://learnxinyminutes.com/docs/p5/" },
    { name = "powershell", path = "https://learnxinyminutes.com/docs/powershell/" },
    { name = "PyQT", path = "https://learnxinyminutes.com/docs/pyqt/" },
    { name = "Qt Framework", path = "https://learnxinyminutes.com/docs/qt/" },
    { name = "ruby ecosystem", path = "https://learnxinyminutes.com/docs/ruby-ecosystem/" },
    { name = "ShutIt", path = "https://learnxinyminutes.com/docs/shutit/" },
    { name = "Statistical Computing with Python", path = "https://learnxinyminutes.com/docs/pythonstatcomp/" },
    { name = "tcsh", path = "https://learnxinyminutes.com/docs/tcsh/" },
    { name = "tmux", path = "https://learnxinyminutes.com/docs/tmux/" },
    { name = "vim", path = "https://learnxinyminutes.com/docs/vim/" },
    { name = "zfs", path = "https://learnxinyminutes.com/docs/zfs/" },
}

return LearnXInYMinutes
