----------------------------------------------------------------------------------------------------
-- IINA application config
--
local Ki = spoon.Ki
local Application = Ki.Application
local FocusAndChooseMenuItem = Application.FocusAndChooseMenuItem
local FocusAndSelectMenuItem = Application.FocusAndSelectMenuItem
local FocusAndToggleMenuItem = Application.FocusAndToggleMenuItem
local unmapped = Application.unmapped

return Application {
    name = "IINA",
    shortcuts = {
        IINA = {
            { nil, ",", FocusAndSelectMenuItem { "IINA", "Preferences…" } },
            { nil, "h", FocusAndSelectMenuItem { "IINA", "Hide IINA" } },
            { nil, "q", FocusAndSelectMenuItem { "IINA", "Quit IINA" } },
            { { "alt" }, "h", FocusAndSelectMenuItem { "IINA", "Hide Others" } },
            { { "alt" }, "q", FocusAndSelectMenuItem { "IINA", "Quit and Keep Windows" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "IINA", "About IINA" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "IINA", "Check for Updates…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "IINA", "Services" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "IINA", "Show All" } },
        },
        File = {
            { nil, "o", FocusAndSelectMenuItem { "File", "Open in New Window…" } },
            { nil, "w", FocusAndSelectMenuItem { "File", "Close" } },
            { { "alt" }, "o", FocusAndSelectMenuItem { "File", "Open…" } },
            { { "alt" }, "w", FocusAndSelectMenuItem { "File", "Close All" } },
            { { "shift" }, "h", FocusAndSelectMenuItem { "File", "Playback History" } },
            { { "shift" }, "o", FocusAndSelectMenuItem { "File", "Open URL in New Window…" } },
            { { "shift", "alt" }, "o", FocusAndSelectMenuItem { "File", "Open URL…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Delete Current File" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "File", "Open Recent" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Save Current Playlist…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Share" } },
        },
        Edit = {
            { nil, "a", FocusAndSelectMenuItem { "Edit", "Select All" } },
            { nil, "c", FocusAndSelectMenuItem { "Edit", "Copy" } },
            { nil, "v", FocusAndSelectMenuItem { "Edit", "Paste" } },
            { nil, "x", FocusAndSelectMenuItem { "Edit", "Cut" } },
            { nil, "z", FocusAndSelectMenuItem { "Edit", "Undo" } },
            { { "shift" }, "z", FocusAndSelectMenuItem { "Edit", "Redo" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Delete" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Emoji & Symbols" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Emoji & Symbols" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Speech" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Start Dictation" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Transformations" } },
        },
        Playback = {
            { nil, "space", FocusAndToggleMenuItem { "Resume", "Pause" } },
            { nil, ".", FocusAndSelectMenuItem { "Playback", "Stop and Clear Playlists" } },
            { nil, "[", FocusAndSelectMenuItem { "Playback", "Speed Down by 0.5x" } },
            { nil, "\\", FocusAndSelectMenuItem { "Playback", "Reset Speed" } },
            { nil, "]", FocusAndSelectMenuItem { "Playback", "Speed Up by 2.0x" } },
            { nil, "j", FocusAndSelectMenuItem { "Playback", "Jump to…" } },
            { nil, "l", FocusAndSelectMenuItem { "Playback", "A-B Loop" } },
            { nil, "n", FocusAndSelectMenuItem { "Playback", "Next Media" } },
            { nil, "p", FocusAndSelectMenuItem { "Playback", "Previous Media" } },
            { nil, "s", FocusAndSelectMenuItem { "Playback", "Take a Screenshot" } },
            { { "alt" }, "[", FocusAndSelectMenuItem { "Playback", "Speed Down by 0.9x" } },
            { { "alt" }, "]", FocusAndSelectMenuItem { "Playback", "Speed Up by 1.1x" } },
            { { "shift" }, "<", FocusAndSelectMenuItem { "Playback", "Previous Chapter" } },
            { { "shift" }, ">", FocusAndSelectMenuItem { "Playback", "Next Chapter" } },
            { { "shift" }, "c", FocusAndSelectMenuItem { "Playback", "Show Chapters Panel" } },
            { { "shift" }, "l", FocusAndSelectMenuItem { "Playback", "File Loop" } },
            { { "shift" }, "p", FocusAndSelectMenuItem { "Playback", "Show Playlist Panel" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Chapters" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Go to Screenshot Folder" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Jump to Beginning" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Next Frame" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Playlist Loop" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Playback", "Playlist" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Previous Frame" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Speed: 1.00x" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Step Backward 5s" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Playback", "Step Forward 5s" } },
        },
        Video = {
            { nil, "-", FocusAndSelectMenuItem { "Video", "Smaller Size" } },
            { nil, "0", FocusAndSelectMenuItem { "Video", "Half Size" } },
            { nil, "1", FocusAndSelectMenuItem { "Video", "Normal Size" } },
            { nil, "2", FocusAndSelectMenuItem { "Video", "Double Size" } },
            { nil, "3", FocusAndSelectMenuItem { "Video", "Fit to Screen" } },
            { nil, "=", FocusAndSelectMenuItem { "Video", "Bigger Size" } },
            { { "alt" }, "1", FocusAndSelectMenuItem { "Video", "Normal Size (Retina)" } },
            { { "alt" }, "m", FocusAndSelectMenuItem { "Video", "Music Mode" } },
            { { "ctrl" }, "f", FocusAndToggleMenuItem { "Enter Full Screen", "Exit Full Screen" } },
            { { "ctrl" }, "p", FocusAndToggleMenuItem { "Enter Picture-in-Picture", "Exit Picture-in-Picture" } },
            { { "ctrl" }, "t", FocusAndSelectMenuItem { "Video", "Float on Top" } },
            { { "ctrl" }, "v", FocusAndSelectMenuItem { "Video", "Cycle Video Tracks" } },
            { { "shift" }, "f", FocusAndSelectMenuItem { "Video", "Video Filters…" } },
            { { "shift" }, "v", FocusAndSelectMenuItem { "Video", "Show Quick Settings Panel" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Video", "Aspect Ratio" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Video", "Crop" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Video", "Deinterlace" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Video", "Delogo" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Video", "Flip" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Video", "Rotation" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Video", "Saved Video Filters" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Video", "Video Track" } },
        },
        Audio = {
            { nil, "/", FocusAndSelectMenuItem { "Audio", "Mute" } },
            { { "ctrl" }, "a", FocusAndSelectMenuItem { "Audio", "Cycle Audio Tracks" } },
            { { "shift" }, "(", FocusAndSelectMenuItem { "Audio", "Audio Delay + 0.5s" } },
            { { "shift" }, ")", FocusAndSelectMenuItem { "Audio", "Audio Delay - 0.5s" } },
            { { "shift" }, "_", FocusAndSelectMenuItem { "Audio", "Reset Audio Delay" } },
            { { "shift" }, "a", FocusAndSelectMenuItem { "Audio", "Show Quick Settings Panel" } },
            { { "shift" }, "g", FocusAndSelectMenuItem { "Audio", "Audio Filters…" } },
            { { "shift", "alt" }, "(", FocusAndSelectMenuItem { "Audio", "Audio Delay + 0.1s" } },
            { { "shift", "alt" }, ")", FocusAndSelectMenuItem { "Audio", "Audio Delay - 0.1s" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Audio", "Audio Delay: 0.00s" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Audio", "Audio Device" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Audio", "Audio Track" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Audio", "Saved Audio Filters" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Audio", "Volume + 1" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Audio", "Volume + 5" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Audio", "Volume - 1" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Audio", "Volume - 5" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Audio", "Volume: 100" } },
        },
        Subtitles = {
            { { "ctrl" }, "s", FocusAndSelectMenuItem { "Subtitles", "Cycle Subtitles" } },
            { { "shift" }, "c", FocusAndSelectMenuItem { "Subtitles", "Reset Subtitle Delay" } },
            { { "shift" }, "d", FocusAndSelectMenuItem { "Subtitles", "Find Online Subtitles…" } },
            { { "shift" }, "s", FocusAndSelectMenuItem { "Subtitles", "Show Quick Settings Panel" } },
            { { "shift" }, "x", FocusAndSelectMenuItem { "Subtitles", "Subtitle Delay + 0.5s" } },
            { { "shift" }, "z", FocusAndSelectMenuItem { "Subtitles", "Subtitle Delay - 0.5s" } },
            { { "shift", "alt" }, "x", FocusAndSelectMenuItem { "Subtitles", "Subtitle Delay + 0.1s" } },
            { { "shift", "alt" }, "z", FocusAndSelectMenuItem { "Subtitles", "Subtitle Delay - 0.1s" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Subtitles", "Encoding" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Subtitles", "Font…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Subtitles", "Load External Subtitle…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Subtitles", "Reset Subtitle Scale" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Subtitles", "Save Downloaded Subtitle" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Subtitles", "Scale Down" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Subtitles", "Scale Up" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Subtitles", "Second Subtitle" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Subtitles", "Subtitle Delay: 0.00s" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Subtitles", "Subtitle" } },
        },
        Window = {
            { nil, "i", FocusAndSelectMenuItem { "Window", "Inspector" } },
            { nil, "m", FocusAndSelectMenuItem { "Window", "Minimize" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Arrange in Front" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Bring All to Front" } },
            { unmapped, unmapped, FocusAndToggleMenuItem { "Enter Full Screen", "Exit Full Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Minimize All" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Left Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Right Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Zoom All" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Zoom" } },
        },
        Help = {
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "GitHub" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "IINA Help" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "Release Highlights" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "Website" } },
        },
    },
}
